apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-texttoservice
spec:
  replicas: 1  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: texttoservice
        image: digit-reader:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 8080